Add coinlore connector
gendzucuuu/crypto-currency-watcher pull request #4
Opened 2022-02-17 22:12 UTC by gendzucuuu

2022-02-25 21:22 UTC, Caromeen requested changes

2022-02-25 21:22 UTC, Caromeen commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/CryptoCurrencyWatcherApplication.java
> +
?

2022-02-25 21:22 UTC, Caromeen commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/connector/impl/CoinloreConnectorImpl.java
> +import lombok.SneakyThrows;
?

2022-02-25 21:22 UTC, Caromeen commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/model/News.java
> +public class News {
?

2022-02-25 21:22 UTC, Caromeen commented on src/test/resources/coinlore/connector/findall/btcresponce.json
> +  {
filenameisnotreadableusesomeseparotorsforexamplefind-allotunderscorefind_allandbtc-responce

2022-04-12 21:01 UTC, gendzucuuu commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/CryptoCurrencyWatcherApplication.java
> +
fixed

2022-04-12 21:02 UTC, gendzucuuu commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/connector/impl/CoinloreConnectorImpl.java
> +import lombok.SneakyThrows;
fixed

2022-04-12 21:02 UTC, gendzucuuu commented on src/main/java/by/gendzucuuu/cryptocurrencywatcher/model/News.java
> +public class News {
deleted

2022-04-12 21:02 UTC, gendzucuuu commented on src/test/resources/coinlore/connector/findall/btcresponce.json
> +  {
fixed

2022-04-12 21:15 UTC, Caromeen approved these changes
Good

2022-04-12 21:15 UTC, merged